export const GET_MOVIE_REQUEST = "GET_MOVIE_REQUEST";
export const GET_MOVIE_SUCCESS = "GET_MOVIE_SUCCESS";
export const GET_MOVIE_ERROR = "GET_MOVIE_ERROR";


export const GET_TRENDING_MOVIE_REQUEST = "GET_TRENDING_MOVIE_REQUEST";
export const GET_TRENDING_MOVIE_SUCCESS = "GET_TRENDING_MOVIE_SUCCESS";
export const GET_TRENDING_MOVIE_ERROR = "GET_TRENDING_MOVIE_ERROR";


export const GET_POPULAR_MOVIE_REQUEST = "GET_POPULAR_MOVIE_REQUEST";
export const GET_POPULAR_MOVIE_SUCCESS = "GET_POPULAR_MOVIE_SUCCESS";
export const GET_POPULAR_MOVIE_ERROR = "GET_POPULAR_MOVIE_ERROR";






