export const GET_TV_SHOW_REQUEST = "GET_TV_SHOW_REQUEST";
export const GET_TV_SHOW_SUCCESS = "GET_TV_SHOW_SUCCESS";
export const GET_TV_SHOW_ERROR = "GET_TV_SHOW_ERROR";


export const GET_TRENDING_TV_SHOW_REQUEST = "GET_TRENDING_TV_SHOW_REQUEST";
export const GET_TRENDING_TV_SHOW_SUCCESS = "GET_TRENDING_TV_SHOW_SUCCESS";
export const GET_TRENDING_TV_SHOW_ERROR = "GET_TRENDING_TV_SHOW_ERROR";


export const GET_POPULAR_TV_SHOW_REQUEST = "GET_POPULAR_TV_SHOW_REQUEST";
export const GET_POPULAR_TV_SHOW_SUCCESS = "GET_POPULAR_TV_SHOW_SUCCESS";
export const GET_POPULAR_TV_SHOW_ERROR = "GET_POPULAR_TV_SHOW_ERROR";
